// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM_V7p4Ciqa3AsAPezXUl-S2pJYrEvmYY',
    appId: '1:513956310524:android:3c35e5f5d071f6e965d679',
    messagingSenderId: '513956310524',
    projectId: 'cookbook-uy',
    storageBucket: 'cookbook-uy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhVQ-xHjZaIDpKlziR_1rmoHVfPQ3GU7E',
    appId: '1:513956310524:ios:8eb4f093eb3c6ca865d679',
    messagingSenderId: '513956310524',
    projectId: 'cookbook-uy',
    storageBucket: 'cookbook-uy.firebasestorage.app',
    iosBundleId: 'com.example.cookbookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhVQ-xHjZaIDpKlziR_1rmoHVfPQ3GU7E',
    appId: '1:513956310524:ios:8eb4f093eb3c6ca865d679',
    messagingSenderId: '513956310524',
    projectId: 'cookbook-uy',
    storageBucket: 'cookbook-uy.firebasestorage.app',
    iosBundleId: 'com.example.cookbookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPNs5LoPcdEXYbd_1BMzUFyldC7UudAfY',
    appId: '1:513956310524:web:555507d0043ce07765d679',
    messagingSenderId: '513956310524',
    projectId: 'cookbook-uy',
    authDomain: 'cookbook-uy.firebaseapp.com',
    storageBucket: 'cookbook-uy.firebasestorage.app',
    measurementId: 'G-533D89BS6Y',
  );
}
